In [1]:
from pathlib import Path
import pandas as pd
import numpy as np

DATASET = Path("datasets/lotto/data_processed.csv")

In [2]:
# Read into data frame
dataset = pd.read_csv(DATASET, header=0, sep=',', quotechar='"', parse_dates=['DrawDate'], dtype={'PrizeType': str})

In [3]:
df = dataset.copy()

In [4]:
df.columns

Index(['DrawNo', 'DrawDate', 'PrizeType', 'LuckyNo', 'DaysSinceLastExactMatch',
       'DaysUntilNextExactMatch', 'DaysSinceLastAnyMatch',
       'DaysUntilNextAnyMatch', '1st_digit', '2nd_digit',
       ...
       'pos_4_0_freq', 'pos_4_1_freq', 'pos_4_2_freq', 'pos_4_3_freq',
       'pos_4_4_freq', 'pos_4_5_freq', 'pos_4_6_freq', 'pos_4_7_freq',
       'pos_4_8_freq', 'pos_4_9_freq'],
      dtype='object', length=115)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104673 entries, 0 to 104672
Columns: 115 entries, DrawNo to pos_4_9_freq
dtypes: datetime64[ns](1), float64(2), int64(111), object(1)
memory usage: 91.8+ MB


In [6]:
#df.dtypes

### Tensor operations

In [16]:
from __future__ import print_function
import operator
import torch
from torch import tensor

In [8]:
m1 = tensor(np.arange(1,10,1))
m1

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
m1.shape

torch.Size([9])

In [10]:
m1.view(3,3)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [11]:
m1.unsqueeze(0)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [12]:
m1.unsqueeze(1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [13]:
m1[None,:]

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [14]:
m1[:, None]

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [20]:
x = torch.empty(1,5,3)
x

tensor([[[ 0.0000e+00, -2.5244e-29,  0.0000e+00],
         [-2.5244e-29,  9.8091e-45,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])

In [22]:
x = torch.rand(5,3)
x

tensor([[0.8623, 0.0754, 0.5937],
        [0.7071, 0.8016, 0.4327],
        [0.2930, 0.0445, 0.1206],
        [0.7341, 0.0319, 0.7804],
        [0.9643, 0.3066, 0.5300]])

In [24]:
x = torch.zeros(5,3, dtype=torch.float)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [26]:
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [28]:
x = x.new_ones(5,3, dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [35]:
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[ 1.3309,  0.6958,  0.1166],
        [-0.5454,  1.3939, -0.2439],
        [-0.0144, -0.7785, -0.5997],
        [-0.1232, -0.6494, -1.9373],
        [ 1.2436, -0.7818,  0.2852]])

In [36]:
x.size()

torch.Size([5, 3])

In [37]:
y = torch.rand(5,3)

In [38]:
x+y

tensor([[ 2.0483,  0.7512,  0.5417],
        [ 0.2989,  1.7430,  0.7087],
        [-0.0063,  0.1233, -0.1910],
        [ 0.6237, -0.1136, -1.5138],
        [ 1.9467, -0.1870,  0.4279]])

In [39]:
torch.add(x,y)

tensor([[ 2.0483,  0.7512,  0.5417],
        [ 0.2989,  1.7430,  0.7087],
        [-0.0063,  0.1233, -0.1910],
        [ 0.6237, -0.1136, -1.5138],
        [ 1.9467, -0.1870,  0.4279]])

In [40]:
print(torch.add(x,y))

tensor([[ 2.0483,  0.7512,  0.5417],
        [ 0.2989,  1.7430,  0.7087],
        [-0.0063,  0.1233, -0.1910],
        [ 0.6237, -0.1136, -1.5138],
        [ 1.9467, -0.1870,  0.4279]])


In [43]:
result = torch.empty(5,3)
torch.add(x,y, out=result)
result

tensor([[ 2.0483,  0.7512,  0.5417],
        [ 0.2989,  1.7430,  0.7087],
        [-0.0063,  0.1233, -0.1910],
        [ 0.6237, -0.1136, -1.5138],
        [ 1.9467, -0.1870,  0.4279]])

In [44]:
y.add_(x)
y

tensor([[ 2.0483,  0.7512,  0.5417],
        [ 0.2989,  1.7430,  0.7087],
        [-0.0063,  0.1233, -0.1910],
        [ 0.6237, -0.1136, -1.5138],
        [ 1.9467, -0.1870,  0.4279]])

In [50]:
z = torch.empty(5,3)
z.copy_(y)
z

tensor([[ 2.0483,  0.7512,  0.5417],
        [ 0.2989,  1.7430,  0.7087],
        [-0.0063,  0.1233, -0.1910],
        [ 0.6237, -0.1136, -1.5138],
        [ 1.9467, -0.1870,  0.4279]])

In [56]:
z.t_()
z

tensor([[ 2.0483,  0.2989, -0.0063,  0.6237,  1.9467],
        [ 0.7512,  1.7430,  0.1233, -0.1136, -0.1870],
        [ 0.5417,  0.7087, -0.1910, -1.5138,  0.4279]])

In [58]:
print(x)
print(x[:,1])

tensor([[ 1.3309,  0.6958,  0.1166],
        [-0.5454,  1.3939, -0.2439],
        [-0.0144, -0.7785, -0.5997],
        [-0.1232, -0.6494, -1.9373],
        [ 1.2436, -0.7818,  0.2852]])
tensor([ 0.6958,  1.3939, -0.7785, -0.6494, -0.7818])


In [61]:
x = torch.rand(4,4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(),y.size(), z.size())
print(x,y,z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[0.2030, 0.8441, 0.5597, 0.0516],
        [0.6370, 0.1916, 0.8966, 0.4050],
        [0.8946, 0.7287, 0.1782, 0.9963],
        [0.6809, 0.2303, 0.9156, 0.8829]]) tensor([0.2030, 0.8441, 0.5597, 0.0516, 0.6370, 0.1916, 0.8966, 0.4050, 0.8946,
        0.7287, 0.1782, 0.9963, 0.6809, 0.2303, 0.9156, 0.8829]) tensor([[0.2030, 0.8441, 0.5597, 0.0516, 0.6370, 0.1916, 0.8966, 0.4050],
        [0.8946, 0.7287, 0.1782, 0.9963, 0.6809, 0.2303, 0.9156, 0.8829]])


In [63]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.1408])
1.140765905380249


In [64]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [65]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [66]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [67]:
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [69]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)


[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [71]:
np.add(a, 1, out=a)

array([2., 2., 2., 2., 2.])

In [72]:
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [73]:
b.storage()

 2.0
 2.0
 2.0
 2.0
 2.0
[torch.DoubleStorage of size 5]

In [74]:
b.abs()

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

$$\| A \|_F = \left( \sum_{i,j=1}^n | a_{ij} |^2 \right)^{1/2}$$


In [77]:
(b*b).sum().sqrt()

tensor(4.4721, dtype=torch.float64)

In [79]:
b.shape

torch.Size([5])

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [81]:
def matmul(a,b):
    ar,ac = a.shape
    br,bc = b.shape
    assert ac==br
    c = torch.zeros(ar, bc)
    for i in range(ar):
        for j in range(bc):
            # Any trailing ",:" can be removed
            c[i,j] = (a[i,:] * b[:,j]).sum()
    return c

In [82]:
m1 = tensor([[1., 2, 3], [4,5,6], [7,8,9]], dtype=torch.float); m1

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [83]:
m2 = tensor([[1., 2, 3], [4,5,6], [7,8,9]], dtype=torch.float); m2

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [84]:
%timeit -n 10 _ = matmul(m1,m2)

424 µs ± 131 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [85]:
#export
def near(a,b): return torch.allclose(a, b, rtol=1e-3, atol=1e-5)
def test_near(a,b): test(a,b,near)

In [142]:
torch.allclose?

Docstring:
allclose(self, other, rtol=1e-05, atol=1e-08, equal_nan=False) -> bool

This function checks if all :attr:`self` and :attr:`other` satisfy the condition:

.. math::
    \lvert \text{self} - \text{other} \rvert \leq \texttt{atol} + \texttt{rtol} \times \lvert \text{other} \rvert

elementwise, for all elements of :attr:`self` and :attr:`other`. The behaviour of this function is analogous to
`numpy.allclose <https://docs.scipy.org/doc/numpy/reference/generated/numpy.allclose.html>`_

Args:
    self (Tensor): first tensor to compare
    other (Tensor): second tensor to compare
    atol (float, optional): absolute tolerance. Default: 1e-08
    rtol (float, optional): relative tolerance. Default: 1e-05
    equal_nan (float, optional): if ``True``, then two ``NaN`` s will be compared as equal. Default: ``False``

Example::

    >>> torch.allclose(torch.tensor([10000., 1e-07]), torch.tensor([10000.1, 1e-08]))
    False
    >>> torch.allclose(torch.tensor([10000., 1e-08]), torch.tens

In [90]:
c = tensor([1,2,3])
c.shape

torch.Size([3])

In [92]:
t = c.expand_as(m1)
t

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [93]:
t.stride()

(0, 1)

### Broadcasting

In [129]:
c[None,:]

tensor([[1, 2, 3]])

In [130]:
c[:, None]

tensor([[1],
        [2],
        [3]])

In [132]:
c[None,:] * c[:,None]

tensor([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])

In [137]:
c[None,:] @ c[:,None]

tensor([[14]])

In [141]:
c[None,:] > c[:, None]

tensor([[0, 1, 1],
        [0, 0, 1],
        [0, 0, 0]], dtype=torch.uint8)

In [95]:
def matmul(a,b):
    ar,ac = a.shape
    br,bc = b.shape
    assert ac==br
    c = torch.zeros(ar, bc)
    for i in range(ar):a
        # c[i,j] = (a[i,:]          * b[:,j]).sum() # previous
        c[i]   = (a[i  ].unsqueeze(-1) * b).sum(dim=0)
    return c

In [98]:
%timeit -n 10 _=matmul(m1,m2)

171 µs ± 75.8 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


### Einstein summation

In [128]:
# c[i,j] += a[i,k] * b[k,j]
# c[i,j] = (a[i,:] * b[:,j]).sum()
def matmul(a,b): return torch.einsum('ik,kj->ij', a, b)

In [103]:
%timeit -n 10 _=matmul(m1,m2)

87.6 µs ± 34.2 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


### pytorch op

In [123]:
%timeit -n 10 m1.matmul(m2)

The slowest run took 31.85 times longer than the fastest. This could mean that an intermediate result is being cached.
33 µs ± 59.2 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [124]:
%timeit -n 10 t2= m1@m2

The slowest run took 110.69 times longer than the fastest. This could mean that an intermediate result is being cached.
61.6 µs ± 135 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [125]:
#test_near(t1,t2)

In [127]:
!python notebook2script.py 01_basic.ipynb

Converted 01_basic.ipynb to exp/nb_01.py


### chain rule