In [1]:
import numpy as np

### Array manipulation

In [4]:
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
arr2D_1 = arr.reshape(3,3)
arr2D_1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
arr2D_2 = np.arange(10,19).reshape(3,3)
arr2D_2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [11]:
np.concatenate((arr2D_1, arr2D_2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [12]:
np.concatenate((arr2D_1, arr2D_2), axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])

In [14]:
np.concatenate((arr2D_1, arr2D_2, arr2D_1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [16]:
# Alternatives
np.vstack((arr2D_1, arr2D_2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [17]:
np.hstack((arr2D_1, arr2D_2))

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])