In [8]:
from sklearn.preprocessing import MultiLabelBinarizer, LabelBinarizer
import numpy as np
import pandas as pd

#### Multi labels

In [14]:
y = [('Texas', 'Florida'), 
    ('California', 'Alabama'), 
    ('Texas', 'Florida'), 
    ('Delware', 'Florida'), 
    ('Texas', 'Alabama')]

one_hot = MultiLabelBinarizer()

# One-hot encode data
print(one_hot.fit_transform(y))

one_hot.classes_

[[0 0 0 1 1]
 [1 1 0 0 0]
 [0 0 0 1 1]
 [0 0 1 1 0]
 [1 0 0 0 1]]


array(['Alabama', 'California', 'Delware', 'Florida', 'Texas'],
      dtype=object)

#### One hot

In [15]:
x = np.array([['Texas'], 
              ['California'], 
              ['Texas'], 
              ['Delaware'], 
              ['Texas']])
one_hot = LabelBinarizer()

# One-hot encode data
one_hot.fit_transform(x)

array([[0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1]])

In [16]:
one_hot.classes_

array(['California', 'Delaware', 'Texas'], dtype='<U10')

In [17]:
x[:, 0]

array(['Texas', 'California', 'Texas', 'Delaware', 'Texas'], dtype='<U10')

In [18]:
pd.get_dummies(x[:,0])

California  Delaware  Texas
0           0         0      1
1           1         0      0
2           0         0      1
3           0         1      0
4           0         0      1