In [1]:
from pathlib import Path
import pandas as pd
import numpy as np

DATASET = Path("datasets/lotto/data_processed.csv")

In [2]:
# Read into data frame
dataset = pd.read_csv(DATASET, header=0, sep=',', quotechar='"', parse_dates=['DrawDate'], dtype={'PrizeType': str})

In [3]:
df = dataset.copy()

In [4]:
df.columns

Index(['DrawNo', 'DrawDate', 'PrizeType', 'LuckyNo', 'DaysSinceLastExactMatch',
       'DaysUntilNextExactMatch', 'DaysSinceLastAnyMatch',
       'DaysUntilNextAnyMatch', '1st_digit', '2nd_digit',
       ...
       'pos_4_0_freq', 'pos_4_1_freq', 'pos_4_2_freq', 'pos_4_3_freq',
       'pos_4_4_freq', 'pos_4_5_freq', 'pos_4_6_freq', 'pos_4_7_freq',
       'pos_4_8_freq', 'pos_4_9_freq'],
      dtype='object', length=115)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104673 entries, 0 to 104672
Columns: 115 entries, DrawNo to pos_4_9_freq
dtypes: datetime64[ns](1), float64(2), int64(111), object(1)
memory usage: 91.8+ MB


In [6]:
#df.dtypes

### pytorch tensor

In [16]:
from __future__ import print_function
import operator
import torch
from torch import tensor

In [8]:
m1 = tensor(np.arange(1,10,1))
m1

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
m1.shape

torch.Size([9])

In [10]:
m1.view(3,3)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [11]:
m1.unsqueeze(0)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [12]:
m1.unsqueeze(1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [13]:
m1[None,:]

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [14]:
m1[:, None]

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [20]:
x = torch.empty(1,5,3)
x

tensor([[[ 0.0000e+00, -2.5244e-29,  0.0000e+00],
         [-2.5244e-29,  9.8091e-45,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])

In [22]:
x = torch.rand(5,3)
x

tensor([[0.8623, 0.0754, 0.5937],
        [0.7071, 0.8016, 0.4327],
        [0.2930, 0.0445, 0.1206],
        [0.7341, 0.0319, 0.7804],
        [0.9643, 0.3066, 0.5300]])

In [24]:
x = torch.zeros(5,3, dtype=torch.float)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [26]:
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [28]:
x = x.new_ones(5,3, dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [35]:
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[ 1.3309,  0.6958,  0.1166],
        [-0.5454,  1.3939, -0.2439],
        [-0.0144, -0.7785, -0.5997],
        [-0.1232, -0.6494, -1.9373],
        [ 1.2436, -0.7818,  0.2852]])

In [36]:
x.size()

torch.Size([5, 3])

In [37]:
y = torch.rand(5,3)

In [38]:
x+y

tensor([[ 2.0483,  0.7512,  0.5417],
        [ 0.2989,  1.7430,  0.7087],
        [-0.0063,  0.1233, -0.1910],
        [ 0.6237, -0.1136, -1.5138],
        [ 1.9467, -0.1870,  0.4279]])

In [39]:
torch.add(x,y)

tensor([[ 2.0483,  0.7512,  0.5417],
        [ 0.2989,  1.7430,  0.7087],
        [-0.0063,  0.1233, -0.1910],
        [ 0.6237, -0.1136, -1.5138],
        [ 1.9467, -0.1870,  0.4279]])

In [40]:
print(torch.add(x,y))

tensor([[ 2.0483,  0.7512,  0.5417],
        [ 0.2989,  1.7430,  0.7087],
        [-0.0063,  0.1233, -0.1910],
        [ 0.6237, -0.1136, -1.5138],
        [ 1.9467, -0.1870,  0.4279]])


In [43]:
result = torch.empty(5,3)
torch.add(x,y, out=result)
result

tensor([[ 2.0483,  0.7512,  0.5417],
        [ 0.2989,  1.7430,  0.7087],
        [-0.0063,  0.1233, -0.1910],
        [ 0.6237, -0.1136, -1.5138],
        [ 1.9467, -0.1870,  0.4279]])

In [44]:
y.add_(x)
y

tensor([[ 2.0483,  0.7512,  0.5417],
        [ 0.2989,  1.7430,  0.7087],
        [-0.0063,  0.1233, -0.1910],
        [ 0.6237, -0.1136, -1.5138],
        [ 1.9467, -0.1870,  0.4279]])

In [50]:
z = torch.empty(5,3)
z.copy_(y)
z

tensor([[ 2.0483,  0.7512,  0.5417],
        [ 0.2989,  1.7430,  0.7087],
        [-0.0063,  0.1233, -0.1910],
        [ 0.6237, -0.1136, -1.5138],
        [ 1.9467, -0.1870,  0.4279]])

In [56]:
z.t_()
z

tensor([[ 2.0483,  0.2989, -0.0063,  0.6237,  1.9467],
        [ 0.7512,  1.7430,  0.1233, -0.1136, -0.1870],
        [ 0.5417,  0.7087, -0.1910, -1.5138,  0.4279]])

In [58]:
print(x)
print(x[:,1])

tensor([[ 1.3309,  0.6958,  0.1166],
        [-0.5454,  1.3939, -0.2439],
        [-0.0144, -0.7785, -0.5997],
        [-0.1232, -0.6494, -1.9373],
        [ 1.2436, -0.7818,  0.2852]])
tensor([ 0.6958,  1.3939, -0.7785, -0.6494, -0.7818])


In [61]:
x = torch.rand(4,4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(),y.size(), z.size())
print(x,y,z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[0.2030, 0.8441, 0.5597, 0.0516],
        [0.6370, 0.1916, 0.8966, 0.4050],
        [0.8946, 0.7287, 0.1782, 0.9963],
        [0.6809, 0.2303, 0.9156, 0.8829]]) tensor([0.2030, 0.8441, 0.5597, 0.0516, 0.6370, 0.1916, 0.8966, 0.4050, 0.8946,
        0.7287, 0.1782, 0.9963, 0.6809, 0.2303, 0.9156, 0.8829]) tensor([[0.2030, 0.8441, 0.5597, 0.0516, 0.6370, 0.1916, 0.8966, 0.4050],
        [0.8946, 0.7287, 0.1782, 0.9963, 0.6809, 0.2303, 0.9156, 0.8829]])


In [63]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.1408])
1.140765905380249


In [64]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [65]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [66]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [67]:
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [69]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)


[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [71]:
np.add(a, 1, out=a)

array([2., 2., 2., 2., 2.])

In [72]:
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [73]:
b.storage()

 2.0
 2.0
 2.0
 2.0
 2.0
[torch.DoubleStorage of size 5]

In [74]:
b.abs()

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)