# LSTM

## Data Preprocessing

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split

In [6]:
path = Path('datasets/equities/mbb.csv')

In [7]:
df = pd.read_csv(path)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1893 entries, 0 to 1892
Data columns (total 7 columns):
Date        1893 non-null object
Price       1893 non-null float64
Open        1893 non-null float64
High        1893 non-null float64
Low         1893 non-null float64
Vol.        1893 non-null object
Change %    1893 non-null object
dtypes: float64(4), object(3)
memory usage: 103.6+ KB


In [14]:
df.head(10)

Date  Price  Open  High   Low    Vol. Change %
0  May 24, 2019   8.99  9.00  9.05  8.96   4.78M   -0.33%
1  May 23, 2019   9.02  8.75  9.10  8.75   9.07M    0.33%
2  May 21, 2019   8.99  9.00  9.04  8.95   5.88M   -0.11%
3  May 17, 2019   9.00  9.00  9.02  8.98   5.44M    0.45%
4  May 16, 2019   8.96  9.01  9.02  8.96   6.56M   -0.55%
5  May 15, 2019   9.01  8.98  9.04  8.95  14.21M    0.56%
6  May 14, 2019   8.96  8.90  8.99  8.90   9.81M   -0.22%
7  May 13, 2019   8.98  8.98  9.00  8.91   9.16M    0.11%
8  May 10, 2019   8.97  8.97  8.99  8.91   9.95M    0.00%
9  May 09, 2019   8.97  8.98  9.00  8.96  11.64M    0.00%

In [17]:
# Convert the date column
df['Date'] = pd.to_datetime(df['Date'])

In [16]:
df.head(10)

Date  Price  Open  High   Low    Vol. Change %
0 2019-05-24   8.99  9.00  9.05  8.96   4.78M   -0.33%
1 2019-05-23   9.02  8.75  9.10  8.75   9.07M    0.33%
2 2019-05-21   8.99  9.00  9.04  8.95   5.88M   -0.11%
3 2019-05-17   9.00  9.00  9.02  8.98   5.44M    0.45%
4 2019-05-16   8.96  9.01  9.02  8.96   6.56M   -0.55%
5 2019-05-15   9.01  8.98  9.04  8.95  14.21M    0.56%
6 2019-05-14   8.96  8.90  8.99  8.90   9.81M   -0.22%
7 2019-05-13   8.98  8.98  9.00  8.91   9.16M    0.11%
8 2019-05-10   8.97  8.97  8.99  8.91   9.95M    0.00%
9 2019-05-09   8.97  8.98  9.00  8.96  11.64M    0.00%

In [19]:
# Sort date column ascending
df.sort_values(by=['Date'], inplace=True)

In [20]:
df.head(10)

Date  Price  Open  High   Low    Vol. Change %
1892 2011-09-02   8.72  9.00  9.00  8.69  12.92M    0.00%
1891 2011-09-05   8.73  8.72  8.75  8.70  12.39M    0.11%
1890 2011-09-06   8.68  8.72  8.72  8.68  11.48M   -0.57%
1889 2011-09-07   8.67  8.70  8.70  8.64   5.73M   -0.12%
1888 2011-09-08   8.69  8.71  8.74  8.67   4.69M    0.23%
1887 2011-09-09   8.69  8.70  8.70  8.68   5.09M    0.00%
1886 2011-09-12   8.61  8.65  8.68  8.55   8.59M   -0.92%
1885 2011-09-13   8.60  8.58  8.61  8.55   3.62M   -0.12%
1884 2011-09-14   8.60  8.64  8.64  8.57  10.24M    0.00%
1883 2011-09-15   8.59  8.62  8.62  8.57   7.59M   -0.12%

In [31]:
# train_test_split?
# Split to training and test set without shuffling
training_set, test_set = train_test_split(df, test_size=0.33, shuffle=False)

In [32]:
training_set.head(10)

Date  Price  Open  High   Low    Vol. Change %
1892 2011-09-02   8.72  9.00  9.00  8.69  12.92M    0.00%
1891 2011-09-05   8.73  8.72  8.75  8.70  12.39M    0.11%
1890 2011-09-06   8.68  8.72  8.72  8.68  11.48M   -0.57%
1889 2011-09-07   8.67  8.70  8.70  8.64   5.73M   -0.12%
1888 2011-09-08   8.69  8.71  8.74  8.67   4.69M    0.23%
1887 2011-09-09   8.69  8.70  8.70  8.68   5.09M    0.00%
1886 2011-09-12   8.61  8.65  8.68  8.55   8.59M   -0.92%
1885 2011-09-13   8.60  8.58  8.61  8.55   3.62M   -0.12%
1884 2011-09-14   8.60  8.64  8.64  8.57  10.24M    0.00%
1883 2011-09-15   8.59  8.62  8.62  8.57   7.59M   -0.12%

In [33]:
test_set.head(10)

Date  Price  Open  High   Low    Vol. Change %
624 2016-10-31   7.90  7.86  7.91  7.81   9.14M    0.89%
623 2016-11-01   7.86  7.89  7.90  7.85   1.70M   -0.51%
622 2016-11-02   7.81  7.86  7.86  7.81   2.74M   -0.64%
621 2016-11-03   7.78  7.81  7.84  7.78   5.50M   -0.38%
620 2016-11-04   7.67  7.76  7.79  7.67   8.54M   -1.41%
619 2016-11-07   7.83  7.69  7.83  7.68   5.80M    2.09%
618 2016-11-08   7.95  7.84  7.95  7.81  16.51M    1.53%
617 2016-11-09   7.87  7.96  7.96  7.79   7.64M   -1.01%
616 2016-11-10   7.96  7.90  8.01  7.89  14.72M    1.14%
615 2016-11-11   7.80  7.93  7.93  7.79  12.21M   -2.01%

In [34]:
# Use the Open price
training_set = training_set.iloc[:,2:3].values
print(training_set)

[[9.  ]
 [8.72]
 [8.72]
 ...
 [7.9 ]
 [7.93]
 [7.8 ]]


In [37]:
# Feature scaling
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
training_set = sc.fit_transform(training_set)
print(training_set)

[[0.45230769]
 [0.36615385]
 [0.36615385]
 ...
 [0.11384615]
 [0.12307692]
 [0.08307692]]


In [39]:
n = len(training_set); n

1268

In [45]:
# Getting the inputs and the ouputs
# Restricting the input and output based on how LSTM functions.
X_train = training_set[0:n-1]
y_train = training_set[1:n]
print(X_train); print(len(X_train))
print(y_train); print(len(y_train))

[[0.45230769]
 [0.36615385]
 [0.36615385]
 ...
 [0.06769231]
 [0.11384615]
 [0.12307692]]
1267
[[0.36615385]
 [0.36615385]
 [0.36      ]
 ...
 [0.11384615]
 [0.12307692]
 [0.08307692]]
1267


In [46]:
# Reshaping - Adding time interval as a dimension for input.
X_train = np.reshape(X_train, (n-1, 1, 1))

In [48]:
print(X_train.shape)

(1267, 1, 1)


## Build the Network

In [49]:
# Importing the Keras libraries and packages
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM

Using TensorFlow backend.


In [55]:
regressor = Sequential()

AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

In [54]:
# 4 memory units, sigmoid activation function and (None time interval with 1 attribute as input)
regressor.add(LSTM(units = 4, activation = 'sigmoid', input_shape = (None, 1)))

NameError: name 'regressor' is not defined

In [53]:
# 1 neuron in the output layer for 1 dimensional output
regressor.add(Dense(units = 1))

NameError: name 'regressor' is not defined

In [56]:
regressor.compile(optimizer = 'adam', loss = 'mean_squared_error')

NameError: name 'regressor' is not defined

In [ ]:
regressor.fit(X_train, y_train, batch_size = 32, epochs = 200)

## Prediction

## Evaluatation

In [59]:
import math
from sklearn.metrics import mean_squared_error
rmse = math.sqrt(mean_squared_error(real_stock_price, predicted_stock_price))
print(rmse)

NameError: name 'real_stock_price' is not defined